### PR TITLE
FAFMIP

### PR DESCRIPTION
**Pull request by rfarneti**
Hi, these are the necessary code changes to run FAFMIP experiments. Two additional tracers have been introduced: redistributed heat and added heat.
cheers, Riccardo

### CODE REVIEW

**Comment by StephenGriffies** [comment]
I thought this code had been merged.  IS there any reason not to do so?  Fabio, have you been testing this code in your simulations?  

If no comments within a day or two, then I will accept the pull request.  So please speak out if you have concerns.

**Comment by fabiobdias** [comment]
Hi @StephenGriffies, yes I have tested it several times and it works fine, no issues.

**Comment by rfarneti** [comment]
Hi,
I also thought this code had been merged long time ago. @StephenGriffies please go ahead.

**Comment by russfiedler** [comment]
@StephenGriffies  Are you sure that it is correct to merge this commit? https://github.com/mom-ocean/MOM5/pull/200 which was a later pull request was merged over a year ago.

It looks like all the files were just put into the top directory and this pull-request was a mistake which was fixed up by the later one.

I recommend reverting.

**Comment by aidanheerdegen** [comment]
This was definitely a duff PR, you can see it has just dumped a bunch of files in the top level:

screen shot 2019-01-10 at 9 46 47 am

So no harm done. I will revert it.

**Comment by russfiedler** [comment]
@StephenGriffies  Yes, the FAFMIP code is already in the main repo and that is what Fabio has been using.

Yes, the existing pull requests need to be sorted out and either include them or a decision is made as to why they are to be rejected.

**Comment by StephenGriffies** [comment]
Thanks @aidanheerdegen for clearing up my muck up here.  Sorry for the bother.  

I suggest there should be some cleanup of the existing pull requests to be sure there is not others that should also be removed...

**Comment by aidanheerdegen** [comment]
@StephenGriffies I reverted that PR following these instructions:

https://help.github.com/articles/reverting-a-pull-request/

Pretty simple actually. You can do it on the command line too, but this was by far the easier option.

I have made a new Issue to address some of your other questions

https://github.com/mom-ocean/MOM5/issues/271

**Comment by StephenGriffies** [comment]
Many thanks @aidanheerdegen

**Comment by fabiobdias** [comment]
Hi @StephenGriffies @rfarneti @russfiedler,

we recently found a bug in our FAFMIP sanity test (i.e. using the 'do_fafmip_heat = .true.' code but with NO flux correction being applied). The redistributed heat (redist_heat) and the prognostic temperature evolve differently and this violates the premises that $\theta$ = T$_{R}$ for this specific experiment (as detailed in the testcase document). 

We tested using conservative and potential temperature but in both cases ‘temp’ is not equal to ‘redist_heat’ from T = 2 and on (only initial condition satisfies that $\theta$ = T$_{R}$). 

figure1_access-om2_temp_pot_temp_redist

**Comment by russfiedler** [comment]
@fabiobdias  Have you actually found a bug or just noted the discrepancy? Also, have you run the short test cases with instantaneous surface fluxes output for the first few time steps that I recommended? It needs to be noted that this is an ACCESS-OM2 run and not a MOM-SIS run.

Do we have a test case for a MOM-SIS run?

**Comment by fabiobdias** [comment]
Hi @russfiedler sorry I'm calling it a bug but I'm not really sure. The thing is that with our ACCESS-OM2 configuration, it is giving wrong results. We haven't tested with MOM-SIS, but I believe @rfarneti did.

@aas0 (Abhishek) has done the test with instantaneou fluxes output - it sits here: /g/data3/hh5/tmp/as7904/output/1deg_jra55_ryf8485_faf_F0_debuging_test/output051/ocean

**Comment by russfiedler** [comment]
Okay, I noted this comment in the frazil module subroutine `compute_frazil_heating`

! Note: unsure if the ACCESS ifedf options have been properly
! handled. Need ACCESS developers to check. 

Unfortunately it's not handled correctly.

If `pop_diag` is true the the code returns before `compute_frazil_redist_heating` is computed. i.e. There's no "formation" of frazil for the redistributed heating.

I'll make this a separate issue.

**Comment by fabiobdias** [comment]
That's great @russfiedler 

By the way it sounds it is an easy fix? Please keep us in the loop so we can test it when available...

Cheers,
Fabio and Abhi

**Pull request merged**
