### PR TITLE
Update FMS with uninitialised variables fixed

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Pull in the FMS branch which has fixed uninitialised variables and added tests for same in FMS CI.

Need a PR here to test the updates in running model.

```
    git subrepo clone --force --branch=cmake git@github.com:mom-ocean/FMS.git src/shared
    
    subrepo:
      subdir:   "src/shared"
      merged:   "d1fa5c6b"
    upstream:
      origin:   "git@github.com:mom-ocean/FMS.git"
      branch:   "cmake"
      commit:   "d1fa5c6b"
    git-subrepo:
      version:  "0.4.0"
      origin:   "https://github.com/ingydotnet/git-subrepo"
      commit:   "5d6aba9"
```

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
@marshallward this is failing because the EBM build uses "-DOVERLOAD_R4", which means it can't find the correct signature for `mpp_type_create` and `mpp_alltoall`:

https://github.com/mom-ocean/MOM5/runs/4502195381?check_suite_focus=true#step:10:166

I've been looking through the code but all the preprocessing stuff does my head in. Do you know an easy fix for this? If not I'll just drop the EBM build from the CI as it is an outlier in this respect.

**Comment by marshallward** [comment]
The real 4 versions exist, but I guess something about OVERLOAD_R4 is hiding them.

for example, `mpp_type_create_real4` is in the `mpp_type_create` interface:

https://github.com/mom-ocean/MOM5/blob/3c6aa016f4871397050f63019b7cca1e7a2771e0/src/shared/mpp/mpp.F90#L574-L581

and is defined here:

https://github.com/mom-ocean/MOM5/blob/3c6aa016f4871397050f63019b7cca1e7a2771e0/src/shared/mpp/include/mpp_comm_mpi.inc#L1276-L1282

using this template include file:

https://github.com/mom-ocean/MOM5/blob/3c6aa016f4871397050f63019b7cca1e7a2771e0/src/shared/mpp/include/mpp_type_mpi.h

As far as I can tell, `FLOAT_KIND` is always 4:

https://github.com/mom-ocean/MOM5/blob/3c6aa016f4871397050f63019b7cca1e7a2771e0/src/shared/include/fms_platform.h#L62-L68

So at the moment, I cannot see why it cannot find the function.  I guess you could search the namespace with `nm` and confirm that the `mpp_type_create_real4` function exists?

**Comment by marshallward** [comment]
Also seems weird to use `-fdefault-real-8` with `OVERLOAD_R4`.

**Comment by aidanheerdegen** [comment]
> Also seems weird to use `-fdefault-real-8` with `OVERLOAD_R4`.

Yeah I noticed that and thought it was weird too. Like it wants to make a an `R4` interface and then promote it to double. I assume it is some legacy cruft, but I'm not minded to spend time trying to figure it out. As there is no easy fix I'll drop EBM from the CI and make an issue, someone else can reinstate it with a PR if they have the inclination.

**Comment by aidanheerdegen** [comment]
Re-cloned the sub-repo from `master` after https://github.com/mom-ocean/FMS/pull/2 was merged.

Ran a jenkins test on the PR and it was fine

https://accessdev.nci.org.au/jenkins/blue/organizations/jenkins/mom-ocean.org%2FMOM5_PR/detail/MOM5_PR/14/pipeline

Will merge so @russfiedler can rebase https://github.com/mom-ocean/MOM5/pull/359 which included some of the uninitialised variables fixed here.

**Pull request merged**
