### PR TITLE
ACCESS CM2 release candidate

### PR DESCRIPTION
**Pull request by aidanheerdegen**
This is the first release candidate for a harmonised ACCESS CM2 version.

I haven't converted all `ACCESS` preprocessor flags yet. This could be done with subsequent commits.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
&#8249;crickets&#8250;

**Comment by marshallward** [comment]
Sorry Aidan, I have family visiting this weekend + Monday, will have a look tomorrow

**Comment by russfiedler** [comment]
@StephenGriffies  Yes, I'm certain about that bug fix in the GOTM wrapper. It came up on the mailing list via Kevin Walsh a couple(?) of years back. Should have been fixed ages ago.

**Comment by aidanheerdegen** [comment]
Thanks for the feedback @StephenGriffies 

Testing is yet to be done. That is the next step before merging the code.

As for bundling, yes I can see the appeal to splitting them, and in fact all these commits could be merged separately, there is no compulsion to squash and merge. Having said which, I have not been very tidy with the commits I am afraid. There is no excuse, just rationalisations which I won't bore you with.

Because we don't have automated testing it is more convenient to test a larger set of changes in one go, and there are some time constraints to try and get this code harmonisation completed for the CSIRO CMIP6 submission.

**Comment by StephenGriffies** [comment]
Thanks for the confirmation @russfiedler 

Time constraints fully understood @aidanheerdegen 

From my perspective I see no problems with this code update.

**Comment by aidanheerdegen** [comment]
Apologies for all the stupid commits, trying to get the travis CI working. Have added a `--no-environ` flag so we can use the same `--platform` flag when compiling stand-alone and in a rose suite, but for the latter if the environment is already set up, want to skip the step sourcing the env file.

**Comment by aidanheerdegen** [comment]
There is an issue comparing `liceht`, as the diagnostic isn't properly coded in the original CM2 MOM5 code correctly, so the field is just missing values in the CM2 runs.

**Comment by aidanheerdegen** [comment]
This is `pme_river` plotted where the harmonised code and the PR code differ, so it is only in the polar regions, but is negative and positive:

image

**Comment by aidanheerdegen** [comment]
I have removed the `do_sfix_at_start` code which reproduced the previous behaviour for testing purposes.

**Pull request merged**
