### PR TITLE
Heat budget diagnostic binned to temperature layers

### PR DESCRIPTION
**Pull request by rmholmes**
This pull request adds a number of diagnostics that output the terms in the heat budget binned to temperature layers using the binning routine diagnose_3d_rho. I have used these in a recent study of heat transport in temperature space in MOM025-SIS and MOM01-SIS. I am adding them here as they could be potentially useful for A. Hogg and K. Stewart in diagnosing implicit mixing in 1-deg runs with varying vertical resolution.

@aidanheerdegen or @nicjhan - can you check these please? I've tested them with Paul's MOM025-SIS, and MOM01-SIS configurations. Let me know if there are any issues.

### CODE REVIEW

**Comment by StephenGriffies** [comment]
This sounds like a great advance in the diagnostic capabilities.  I do not have time to examine the pull request.  My only concern is that it not damage any of the isopycnal/neutral capabilities.  I assume such, but wish to get a confirmation.

**Comment by aidanheerdegen** [comment]
Maybe @russfiedler can take a look?

**Comment by russfiedler** [comment]
The first thing that worries me is that it looks like you can only perform the diagnostics on neutral density surfaces or on temperature but not both. I really dislike the idea of setting a density field to temperature. It really looks like a hack. There might be a way of doing this generically which would be nicer. Also, amusingly, if a linear equation of state is used it looks like  you can't do this binning to temperatures! The IF blocks in ocean_density.F90 need to be reworked.

**Comment by rmholmes** [comment]
Thanks @russfiedler 

Good point on the linear EOS. I've flipped the if statement around so it works now.

Yes this replaces all neutral density binning with temperature binning. So if neutral_rho_equal_theta=.true. then the neutral density diagnostics won't work as expected. For example, tytrans_nrho will be the transport in temperature layers instead of density layers (which is actually quite useful). 

I agree, it should be easy to do this more generically. So if we're not happy with this approach I will keep it in my branch until I have time to look at it again. Sorry! I intend to get back to this at some point because we have some ideas about binning in T and S at the same time. For now I will work with Andy and Kial directly to get these diagnostics out of their simulations.

**Comment by StephenGriffies** [comment]
I support adding the code now.  It only adds a new option, and does not break an old option.  More general approach would be nice so that multiple binning is possible.  But that is not necessary to support including a new diagnostic that is both useful and does not break anything already there. 

So I recommend accepting the merge.

**Comment by rmholmes** [comment]
Given Steve's comment, I have reopened.

**Pull request merged**
