### PR TITLE
APE changes #210

### PR DESCRIPTION
**Pull request by fabiobdias**

### CODE REVIEW

**Comment by StephenGriffies** [comment]
This pull request has sat for three weeks.  It is needed for ongoing science.  So I just merged this pull request, as it has no conflicts.  @fabiobdias please test to ensure that all is fine.

**Comment by aidanheerdegen** [comment]
Is this the pull request you were talking about in the MOM meeting @fabiobdias?

**Comment by fabiobdias** [comment]
Yes it is exatcly this one @aidanheerdegen
These mods was done by Paul Spence a while ago... I just implemented it in a newer mom5 version.

**Comment by aidanheerdegen** [comment]
Great.

**Comment by StephenGriffies** [comment]
Can we please be sure these changes work in all test cases?  Were the automatic tests run?  

Sorry, but I did not run tests before accepting this pull request.  Instead, I wanted to get Fabio moving on this work sooner than later.  Nonetheless, we need to ensure the updates did not mess with anything.

**Comment by aidanheerdegen** [comment]
ping @nicjhan

**Pull request merged**
