### PR TITLE
Update license to LGPLv3

### LINKED ISSUE #370: License change/update
The license was set to GNU GPLv2 by Tim Leslie in 20212:

https://github.com/mom-ocean/MOM5/commit/9ae02a3f0525ce78172d333712b60d8578494ade

MOM6 changed their license to GNU LGPLv3 to allow it to be used as part of a coupled modelling system:

https://github.com/mom-ocean/MOM6/issues/580

Should we make the same change to MOM5 as it is used in coupled models? I'm thinking particularly of the ACCESS models utilising the UM. In the case I don't *think* it is an issue as the model isn't distributed as such because of the UM license. Nonetheless it would be good to have the licence changed to better reflect how the code is used.

@StephenGriffies should have the final say.

Having said which, I have no idea how hard or easy that is. The MOM6 folks got the permission for all contributors. I'll ping all of them here and see who responds, and have a discussion.

@timleslie @marshallward @nichannah @russfiedler @aekiss @rmholmes @hailinyan @rfarneti @penguian @KateSnow @dhruvbhagtani @underwoo @zliang @adele157 @naught101 @castelao

### PR DESCRIPTION
**Pull request by aidanheerdegen**
As per https://choosealicense.com/licenses/lgpl-3.0/ the GNU preferred method is to have two files, COPYING and COPYING.LESSER, as the LGPL is merely a modification of the GPL it requires a full copy of the GPL also be included.

License is detected by GitHub, though as LGPL-3.0 + GPL-3.0.

Closes #370

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
If anyone else wants to be added as a reviewer to add their approval, happy to do so. Just didn't want to burden too many people.

**Comment by aekiss** [comment]
Seems fine to me, but I'm not expert. @micaeljtoliveira - what do you think?

**Review by aekiss — APPROVED** [review]

**Review by marshallward — APPROVED** [review]
Did not know about the `COPYING` + `COPYING.LESSER` thing, but :shrug:

**Comment by aidanheerdegen** [comment]
@StephenGriffies Would you mind officially approving this (changing the license to LGPLv3). Thanks.

**Comment by StephenGriffies** [comment]
Thanks to everyone working through these rather tedious issues.

**Pull request merged**
