### PR TITLE
FMS subtree

### PR DESCRIPTION
**Pull request by aidanheerdegen**
This is a test of using `subtree` to make it easier to update the FMS source code.

The files in the `src/shared` directory have been replaced using a call to [subrepo](https://github.com/ingydotnet/git-subrepo)
```
git subrepo clone git@github.com:mom-ocean/FMS.git src/shared
```
This has replaced all the files with those from the `master` branch of the [mom-ocean fork of FMS](https://github.com/mom-ocean/FMS)

Some other changes were required, moving the `git` version module out of `src/shared/version` to `src/version`. 

Apart from a few changes to the compilation scripts it seemed to work pretty smoothly.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
I reverted the FMS version to the most recent `ulm` tag on the FMS fork
```
git subrepo clone --force -b ulm_201510 git@github.com:mom-ocean/FMS.git src/shared
```
and the issues with the EBM build went away. They appear to be associated with some changes @marshallward put in for `alltoall_w`.

Ok, I need a reviewe. Any volunteers? @russfiedler? @marshallward? @angus-g?

Also how to test this? Any suggestions or anyone putting up their hand to run some tests?

**Comment by marshallward** [comment]
Can you copy the errors?  I may recognise them.

**Comment by marshallward** [comment]
Repeating some relevant info from Slack:

There are potiential fixes to alltoallw, mpp_global_sum, and mpp_type here:

https://github.com/NOAA-GFDL/FMS/pull/99

Also, it seems that EBM requires a module `atmos_ocean_fluxes_mod` which has been removed from FMS.  (There is a broader effort to remove a lot of this model-specific support code from FMS, BTW).  So we'll probably need to manually re-add this module and test that it works under the new FMS.

**Comment by aidanheerdegen** [comment]
It was decided this PR should recreate the current `src/shared` source tree as faithfully as possible. After some detective work it seems Marshall cloned from the `ulm_201505` commit.

https://github.com/mom-ocean/FMS/tree/ulm_201505

I made a branch on the FMS fork which reproduced all of Marshall's changes

https://github.com/mom-ocean/FMS/tree/MOM5_ulm_update

And then replace the current subtree with the new branch

```bash
$ git subrepo clone --force -b MOM5_ulm_update git@github.com:mom-ocean/FMS.git src/shared
Subrepo 'git@github.com:mom-ocean/FMS.git' (MOM5_ulm_update) recloned into 'src/shared'.
```

**Comment by aidanheerdegen** [comment]
The run tests for `om3_core3` and `global_0.25_degree_NYF` are also passing:

https://accessdev.nci.org.au/jenkins/blue/organizations/jenkins/mom-ocean.org%2FMOM5_PR/detail/MOM5_PR/9/pipeline

**Comment by aidanheerdegen** [comment]
The `src/shared` directories are now identical, except for moving the `src/shared/version` stuff out of the FMS subdirectory into it's own directory in `src/version`.

@russfiedler do you have time to have a quick look to make sure I haven't done anything too stupid. I rebased the code to a more recent commit which is why I think there are some seemingly unrelated commits in there.

@marshallward if you have any opinions I'd be happy to hear them as this is just recreating what you did. It appears there were some `alltoall` changes in there as well as updating to `ulm`.

So, the code in `src/shared` SHOULD NOT BE CHANGED IN THIS REPO!

It needs to be modified in the FMS fork and the use `subtree` to clone in a modified version.

This should make it a lot easier to add @marshallward and @rxy900 PIO changes

https://github.com/NOAA-GFDL/FMS/pull/74

https://github.com/NOAA-GFDL/FMS/tree/with-parallel-netcdf

**Comment by marshallward** [comment]
I see a lot of `if (from_pe /= NULL_PE)` if-blocks removed.  I would guess this is related to the case where an entire PE domain gets removed by land.

I can only assume this is not a problem, particularly if it's identical to the existing FMS, might be good to check that a land-masked run still works.

Also, was the git hash supposed to be hard-coded into the source?  AFAIK that is generated by the build scripts?

**Comment by aidanheerdegen** [comment]
Thanks for looking @marshallward 

Yeah you're right that `version.f90` is generated at compile time. I'll remove it.

Should have said this intended to reproduce some of this PR https://github.com/mom-ocean/MOM5/pull/132, namely the bits contained within the `src/shared` directory.

I think the quarter degree test ran ok, but yeah it isn't masked. Should make a masked version as that is exercising many other branches of the code.

**Comment by aidanheerdegen** [comment]
Ok, also passes bit repro tests for `om3_core3` and `global_0.25_degree_NYF`

I will look into adding masking to the quarter degree test case.

**Comment by aidanheerdegen** [comment]
If @nichannah needs this to test the parallel netCDF and it is holding him up then it is ok to merge IMO.

**Comment by marshallward** [comment]
It's unlikely that there is any problem, if it's the same FMS that you all have been using, so probably OK.

This is starting to come back to me, I think those `NULL_PE` checks were causing some of the test to hang, and removing them fixed the issue for me.  Perhaps something about the PE lists changed, I am not sure.

**Comment by aidanheerdegen** [comment]
I created a masked version of `global_0.25_degree_NYF` and ran it. It didn't crash. The checksums don't match because I've not run with bit repro flags.

Is that enough of a test @marshallward? Or do I need to test against all the cases?

**Comment by marshallward** [comment]
No I think that should be fine.

**Comment by aidanheerdegen** [comment]
Aaarrggghh! Realised I am recreating the `shared` directory at the point you updated to `ulm`, but there are commits after this point of course:

```
commit 34408e33e5b4c874c90cc3823bb8c5137961c97f
Author: Nic Hannah <nichannah@pm.me>
Date:   Fri Nov 30 10:51:19 2018 +1100

    Variable renaming and print out commit hash on startup. Closes #261

commit eddccb2f8707506e59b0a5c52e504aaff7127758
Author: Fiedler, Russell (CMAR, Hobart) <Russell.Fiedler@csiro.au>
Date:   Mon Jan 8 13:44:32 2018 +1100

    Add explicit stack trace for intel compiler from PE that issues FATAL

commit 4745c52aeb8bfb702635113d4e724d12bf9c67bd
Author: Nicholas Hannah <nic@doubleprecision.com.au>
Date:   Mon Jul 24 15:53:11 2017 +1000

    Check for NULL_PE when doing mpp global field. Closes #183

commit 94b2c19f058ba453b7a929adc1170b67ddc17182
Author: Nicholas Hannah <nic@doubleprecision.com.au>
Date:   Tue Jun 27 14:41:15 2017 +1000

    Reduce hard-code maximum number of restart fields. This improves memory performance. #177

commit 806d881f80e3c123e2149fcb32b79ca08f742394
Author: Marshall Ward <marshall.ward@gmail.com>
Date:   Fri Jul 29 10:33:52 2016 +1000

    field manager maximum field update

commit 6ef5ccbceddefbebeae53c28f5f058def8ca8f0b
Author: Marshall Ward <marshall.ward@gmail.com>
Date:   Tue Apr 12 12:12:14 2016 +1000

    xgrid.f90 update; restore fms_io_nml flags
    
    The alltoall-based exchange grid calculation is restored in this
    commit.  It is based on the development version of FMS, since it has not
    yet been integrated into the Ulm release.  It is based on the current
    Alltoall implementation in the repo, with some minor changes by Zhi
    Liang.
    
    The following deprecated FMS IO namelist settings have also been
    restored:
    
    * ``threading_write``
    * ``fileset_write``

```

I will add these changes to the FMS fork I am using for the subtree and re clone

https://github.com/mom-ocean/FMS/tree/MOM5_ulm_update

**Comment by aidanheerdegen** [comment]
Changes added redoing subtree clone

git subrepo clone --force -b MOM5_ulm_update git@github.com:mom-ocean/FMS.git src/shared

**Comment by aidanheerdegen** [comment]
In all respects that are important `src/shared` is identical to the my `master` branch commit id ae0da9b8c89bbc2893816bb8c80ba3fc5bc33dbe

**Comment by aidanheerdegen** [comment]
Ok, I'm going to merge now.

**Pull request merged**
