### PR TITLE
CM2

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Updated CM2 Pull request after rebasing.

### CODE REVIEW

**Comment by russfiedler** [comment]
The variable background vertical mixing code in tidal mixing module gets turned on automatically unless you choose the coefficients carefully. There should be a flag in the namelist to enable this feature. The default should be false in order to preserve old behaviour.

**Comment by aidanheerdegen** [comment]
@russfiedler The standard version does seem to have `diff_cbt_conv`

https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_param/vertical/ocean_vert_mix.F90#L2946

But I have stuffed up the call. Not sure why that compiled to be honest. Will fix.

**Comment by aidanheerdegen** [comment]
The double call to `wscale` is in the CSIRO code

https://github.com/peterdobro/mom/blob/master/src/mom5/ocean_param/vertical/ocean_vert_kpp_mom4p1.F90#L1698

I figured I'd let them sort it out.

**Comment by aidanheerdegen** [comment]
I have fixed the ghats error. Thanks @russfiedler. If it helps you can see the logic in the CSIRO version here

https://github.com/peterdobro/mom/blob/master/src/mom5/ocean_param/vertical/ocean_vert_kpp_mom4p1.F90#L2778

I made a mistake with the preprocessing flags and removed it entirely. I have now made a very ugly thing which does what the CSIRO code does by just not every hitting the first branch of the if statement.

**Comment by ofa001** [comment]
Wasn’t diff_cbt_conv  an addition of paul Spence’s so it wouldn’t be in our coupled version it went in later after our branch split from yours in 2014/5 I couldn’t fint it when I did a quick look at lunchtime.

**Comment by aidanheerdegen** [comment]
You're correct Siobhan, it is the APE diagnostic but Fabio coded it:

https://github.com/mom-ocean/MOM5/issues/210

**Comment by ofa001** [comment]
Ok It was Paul who told me about one he had, that he could give me when we were discussing an over convective Southern ocean a couple of years back, its likely Fabio did one as well for his heat budgets.  I was just looking at the total diffusion which was dominated by convection!

**Comment by aidanheerdegen** [comment]
Old PR. Harmonised code was successfully merged in https://github.com/mom-ocean/MOM5/pull/251

**Pull request closed without merging**
