### PR TITLE
Bug fix regarding https://github.com/COSIMA/access-om2/issues/282

### PR DESCRIPTION
**Pull request by hakaseh**
…COSIMA/access-om2/issues/282
@dougiesquire did I create a pull request in the right place??

### CODE REVIEW

**Comment by dougiesquire** [comment]
Thanks @hakaseh. Yes, I'll try to get to a review soon (I'd like to confirm for myself one last time that this is needed)

**Review by dougiesquire — APPROVED** [review]
Thanks @hakaseh - looks good to me!

**Comment by dougiesquire** [comment]
@aekiss, @aidanheerdegen would one of you mind (reviewing and) merging?

**Comment by aekiss** [comment]
Thanks @hakaseh, @dougiesquire I'm happy to merge since this looks ok to you both.

**Comment by pwongpan** [comment]
Thanks again all.

**Pull request merged**
